// This source code is based on https://justsimplycode.com/2020/12/06/auto-generate-builders-using-source-generator-in-net-5

using FluentBuilderGenerator.Models;
using FluentBuilderGenerator.Types;

namespace FluentBuilderGenerator.FileGenerators;

internal class AutoGenerateBuilderAttributeGenerator : IFileGenerator
{
    private const string Name = "FluentBuilder.AutoGenerateBuilderAttribute.g.cs";

    public FileData GenerateFile()
    {
        return new FileData
        (
            FileDataType.Attribute,
            Name,
            @"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/FluentBuilder.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace FluentBuilder
{
    [AttributeUsage(AttributeTargets.Class)]
    sealed class AutoGenerateBuilderAttribute : Attribute
    {
        public AutoGenerateBuilderAttribute() {}
    }
}"
        );
    }
}