// This source code is based on https://justsimplycode.com/2020/12/06/auto-generate-builders-using-source-generator-in-net-5
using System.Text;
using FluentBuilderGenerator.Extensions;
using FluentBuilderGenerator.Helpers;
using FluentBuilderGenerator.Models;
using FluentBuilderGenerator.SyntaxReceiver;
using FluentBuilderGenerator.Types;
using FluentBuilderGenerator.Wrappers;
using Microsoft.CodeAnalysis;

namespace FluentBuilderGenerator.FileGenerators;

internal partial class FluentBuilderClassesGenerator : IFilesGenerator
{
    private static readonly string[] FluentBuilderIgnoreAttributeClassNames =
    {
        "FluentBuilder.FluentBuilderIgnoreAttribute",
        "FluentBuilderIgnoreAttribute",
        "FluentBuilder.FluentBuilderIgnore",
        "FluentBuilderIgnore"
    };

    private static readonly string[] SystemUsings =
    {
        "System",
        "System.Collections",
        "System.Collections.Generic",
        "System.Reflection"
    };

    private static readonly FileDataType[] ExtraBuilders =
    {
        FileDataType.ArrayBuilder,
        FileDataType.IEnumerableBuilder,
        FileDataType.IListBuilder,
        FileDataType.ICollectionBuilder
    };

    private readonly IGeneratorExecutionContextWrapper _context;
    private readonly IAutoGenerateBuilderSyntaxReceiver _receiver;

    public FluentBuilderClassesGenerator(IGeneratorExecutionContextWrapper context, IAutoGenerateBuilderSyntaxReceiver receiver)
    {
        _context = context;
        _receiver = receiver;
    }

    public IReadOnlyList<FileData> GenerateFiles()
    {
        var applicableClassSymbols = GetClassSymbols();
        var extraClassSymbols = applicableClassSymbols.Select(x => x.ClassSymbol).ToList();

        var classes = applicableClassSymbols.Select(classSymbol => new FileData
        (
            FileDataType.Builder,
            $"{classSymbol.ClassSymbol.FullBuilderClassName.Replace('<', '_').Replace('>', '_')}.g.cs",
            CreateClassBuilderCode(classSymbol.FluentData, classSymbol.ClassSymbol, extraClassSymbols)
        ));

        // Extra
        var extra = extraClassSymbols
            .Where(e => ExtraBuilders.Contains(e.Type))
            .OrderBy(e => e.Type)
            .Select(classSymbol => new FileData
            (
                classSymbol.Type,
                $"{classSymbol.NamedTypeSymbol.GenerateFileName()}_{classSymbol.Type}.g.cs",
                CreateIEnumerableBuilderCode(classSymbol)
            ));

        return classes.Union(extra).ToList();
    }

    private string CreateClassBuilderCode(FluentData fluentData, ClassSymbol classSymbol, List<ClassSymbol> allClassSymbols)
    {
        var property = GenerateWithPropertyCode(fluentData, classSymbol, allClassSymbols);

        var usings = SystemUsings.ToList();
        usings.Add($"{_context.AssemblyName}.FluentBuilder");
        usings.Add($"{classSymbol.NamedTypeSymbol.ContainingNamespace}");
        usings.AddRange(property.ExtraUsings);

        var usingsAsStrings = string.Join("\r\n", usings.Distinct().Select(u => $"using {u};"));

        return $@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/FluentBuilder version {System.Reflection.Assembly.GetExecutingAssembly().GetName().Version}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

{(_context.SupportsNullable ? "#nullable enable" : string.Empty)}
{usingsAsStrings}

namespace {classSymbol.BuilderNamespace}
{{
    public partial class {classSymbol.BuilderClassName} : Builder<{classSymbol.NamedTypeSymbol}>{classSymbol.NamedTypeSymbol.GetWhereStatement()}
    {{
{property.StringBuilder}
{GenerateBuildMethod(fluentData, classSymbol)}
    }}
}}
{(_context.SupportsNullable ? "#nullable disable" : string.Empty)}";
    }

    private (StringBuilder StringBuilder, IReadOnlyList<string> ExtraUsings) GenerateWithPropertyCode(
        FluentData fluentData,
        ClassSymbol classSymbol,
        List<ClassSymbol> allClassSymbols)
    {
        var className = classSymbol.BuilderClassName;

        var (propertiesPublicSettable, propertiesPrivateSettable) = GetProperties(classSymbol, fluentData.HandleBaseClasses, fluentData.Accessibility);
        
        var extraUsings = new List<string>();

        var sb = new StringBuilder();
        foreach (var property in propertiesPublicSettable.Union(propertiesPrivateSettable))
        {
            // Use "params" in case it's an Array, else just use type-T.
            var type = property.Type.GetFluentTypeKind() == FluentTypeKind.Array ? $"params {property.Type}" : property.Type.ToString();

            var (defaultValue, extraUsingsFromDefaultValue) = DefaultValueHelper.GetDefaultValue(property);
            if (extraUsingsFromDefaultValue != null)
            {
                extraUsings.AddRange(extraUsingsFromDefaultValue);
            }

            sb.AppendLine($"        private bool _{CamelCase(property.Name)}IsSet;");

            sb.AppendLine($"        private Lazy<{property.Type}> _{CamelCase(property.Name)} = new Lazy<{property.Type}>(() => {defaultValue});");

            sb.AppendLine($"        public {className} With{property.Name}({type} value) => With{property.Name}(() => value);");

            sb.Append(GenerateWithPropertyFuncMethod(classSymbol, property));

            sb.Append(GeneratePropertyActionMethodIfApplicable(classSymbol, property, allClassSymbols));

            sb.AppendLine($"        public {className} Without{property.Name}()");
            sb.AppendLine("        {");
            sb.AppendLine($"            With{property.Name}(() => {defaultValue});");
            sb.AppendLine($"            _{CamelCase(property.Name)}IsSet = false;");
            sb.AppendLine("            return this;");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        return (sb, extraUsings.Distinct().ToList());
    }

    private StringBuilder GeneratePropertyActionMethodIfApplicable(
        ClassSymbol classSymbol,
        IPropertySymbol property,
        List<ClassSymbol> allClassSymbols)
    {
        var existingClassSymbol = allClassSymbols.FirstOrDefault(c => c.NamedTypeSymbol.Name == property.Type.Name);
        if (existingClassSymbol is not null)
        {
            return GenerateWithPropertyActionMethod(classSymbol, existingClassSymbol, property);
        }

        if (property.TryGetIDictionaryElementTypes(out var dictionaryTypes))
        {
            return GenerateWithIDictionaryBuilderActionMethod(classSymbol, property, dictionaryTypes);
        }

        if (property.TryGetIEnumerableElementType(out var elementType, out var kind))
        {
            return GenerateWithIEnumerableBuilderActionMethod(kind, classSymbol, property, elementType, allClassSymbols);
        }

        return new StringBuilder();
    }

    private static StringBuilder GenerateWithPropertyFuncMethod(ClassSymbol classSymbol, IPropertySymbol property)
    {
        var className = classSymbol.BuilderClassName;

        return new StringBuilder()
            .AppendLine($"        public {className} With{property.Name}(Func<{property.Type}> func)")
            .AppendLine("        {")
            .AppendLine($"            _{CamelCase(property.Name)} = new Lazy<{property.Type}>(func);")
            .AppendLine($"            _{CamelCase(property.Name)}IsSet = true;")
            .AppendLine("            return this;")
            .AppendLine("        }");
    }

    private static StringBuilder GenerateWithPropertyActionMethod(ClassSymbol classSymbol, ClassSymbol propertyClassSymbol, IPropertySymbol property)
    {
        var className = classSymbol.BuilderClassName;
        var builderName = propertyClassSymbol.FullBuilderClassName;

        // Replace MyAddressBuilder<T> by MyAddressBuilder<short>
        if (property.Type is INamedTypeSymbol propertyNamedType && builderName.TryGetGenericTypeArguments(out var genericTypeArgumentValue))
        {
            var list = propertyNamedType.TypeArguments.Select(t => t.ToString());
            builderName = builderName.Replace($"<{genericTypeArgumentValue}>", $"<{string.Join(", ", list)}>");
        }

        return new StringBuilder()
            .AppendLine($"        public {className} With{property.Name}(Action<{builderName}> action, bool useObjectInitializer = true) => With{property.Name}(() =>")
            .AppendLine("        {")
            .AppendLine($"            var builder = new {builderName}();")
            .AppendLine("            action(builder);")
            .AppendLine("            return builder.Build(useObjectInitializer);")
            .AppendLine("        });");
    }

    private StringBuilder GenerateWithIEnumerableBuilderActionMethod(
        FluentTypeKind kind,
        ClassSymbol classSymbol,
        IPropertySymbol property,
        INamedTypeSymbol? typeSymbol,
        List<ClassSymbol> allClassSymbols)
    {
        var className = classSymbol.BuilderClassName;
        var typeSymbolClassName = typeSymbol?.GenerateShortTypeName();
        var existingClassSymbol = allClassSymbols.FirstOrDefault(c => c.NamedTypeSymbol.Name == typeSymbolClassName);

        string fullBuilderName;
        if (existingClassSymbol != null && typeSymbol != null)
        {
            var shortBuilderName = $"{kind}{typeSymbol.GenerateShortTypeName(true)}";
            fullBuilderName = $"{typeSymbol.ContainingNamespace}.{shortBuilderName}";
            if (allClassSymbols.All(cs => cs.NamedTypeSymbol.Name != shortBuilderName))
            {
                var fileDataType = kind.ToFileDataType();
                allClassSymbols.Add(new ClassSymbol
                {
                    Type = fileDataType,
                    BuilderNamespace = existingClassSymbol.BuilderNamespace,
                    BuilderClassName = shortBuilderName,
                    FullBuilderClassName = fullBuilderName,
                    NamedTypeSymbol = typeSymbol
                });
            }
        }
        else
        {
            // Normal
            fullBuilderName = $"{_context.AssemblyName}.FluentBuilder.{kind}Builder{(typeSymbol == null ? string.Empty : "<" + typeSymbol.GenerateFullTypeName() + ">")}";
        }

        // If the property.Type is an interface or array, no cast is needed. Else cast the interface to the real type.
        var cast = property.Type.TypeKind is TypeKind.Interface or TypeKind.Array ?
            string.Empty :
            $"({property.Type}) ";

        return new StringBuilder()
            .AppendLine($"        public {className} With{property.Name}(Action<{fullBuilderName}> action, bool useObjectInitializer = true) => With{property.Name}(() =>")
            .AppendLine("        {")
            .AppendLine($"            var builder = new {fullBuilderName}();")
            .AppendLine("            action(builder);")
            .AppendLine($"            return {cast}builder.Build(useObjectInitializer);")
            .AppendLine("        });");
    }

    private static (IReadOnlyList<IPropertySymbol> PublicSettable, IReadOnlyList<IPropertySymbol> PrivateSettable) GetProperties(ClassSymbol classSymbol, bool handleBaseClasses, FluentBuilderAccessibility accessibility)
    {
        var properties = classSymbol.NamedTypeSymbol.GetMembers().OfType<IPropertySymbol>()
            .Where(x => x.SetMethod is not null)
            .Where(x => x.CanBeReferencedByName)
            .Where(x => !x.GetAttributes().Any(a => FluentBuilderIgnoreAttributeClassNames.Contains(a.AttributeClass?.GetFullType())))
            .ToList();

        var propertyNames = properties.Select(x => x.Name);

        if (handleBaseClasses)
        {
            var baseType = classSymbol.NamedTypeSymbol.BaseType;

            while (baseType != null)
            {
                properties.AddRange(baseType.GetMembers().OfType<IPropertySymbol>()
                    .Where(x => x.CanBeReferencedByName)
                    .Where(x => x.SetMethod is not null)
                    .Where(x => !propertyNames.Contains(x.Name)));

                baseType = baseType.BaseType;
            }
        }

        var propertiesPublicSettable = properties.Where(property => property.IsPublicSettable()).ToArray();
        var propertiesPrivateSettable = accessibility.HasFlag(FluentBuilderAccessibility.Private) ?
            properties.Where(property => property.IsPrivateSettable()).ToArray() : Array.Empty<IPropertySymbol>();

        return (propertiesPublicSettable, propertiesPrivateSettable);
    }

    private static string GenerateBuildMethod(FluentData fluentData, ClassSymbol classSymbol)
    {
        if (!classSymbol.NamedTypeSymbol.Constructors.Any(c => c.DeclaredAccessibility == Accessibility.Public && c.Parameters.IsEmpty))
        {
            throw new NotSupportedException($"Unable to generate a FluentBuilder for the class '{classSymbol.NamedTypeSymbol}' because no public parameterless constructor was defined.");
        }

        var (propertiesPublicSettable, propertiesPrivateSettable) = GetProperties(classSymbol, fluentData.HandleBaseClasses, fluentData.Accessibility);
        var className = classSymbol.NamedTypeSymbol.GenerateShortTypeName();

        var output = new StringBuilder();

        foreach (var property in propertiesPrivateSettable)
        {
            BuildPrivateSetMethod(output, className, property);
        }

        output.AppendLine($@"        public override {className} Build(bool useObjectInitializer = true)
        {{
            if (Object?.IsValueCreated != true)
            {{
                Object = new Lazy<{className}>(() =>
                {{
                    {className} instance;
                    if (useObjectInitializer)
                    {{
                        instance = new {className}
                        {{");
        output.AppendLines(propertiesPublicSettable.Select(property => $@"                            {property.Name} = _{CamelCase(property.Name)}.Value"), ",");
        output.AppendLine("                        };");

        output.AppendLines(propertiesPrivateSettable.Select(property => $@"                        if (_{CamelCase(property.Name)}IsSet) {{ Set{property.Name}(instance, _{CamelCase(property.Name)}.Value); }}"));

        output.AppendLine("                        return instance;");
        output.AppendLine("                    }");
        output.AppendLine($@"
                    instance = new {className}();");

        output.AppendLines(propertiesPublicSettable.Select(property => $@"                    if (_{CamelCase(property.Name)}IsSet) {{ instance.{property.Name} = _{CamelCase(property.Name)}.Value; }}"));

        output.AppendLines(propertiesPrivateSettable.Select(property => $@"                    if (_{CamelCase(property.Name)}IsSet) {{ Set{property.Name}(instance, _{CamelCase(property.Name)}.Value); }}"));

        output.AppendLine($@"                    return instance;
                }});
            }}

            PostBuild(Object.Value);

            return Object.Value;
        }}

        public static {className} Default() => new {className}();");

        return output.ToString();
    }

    private static void BuildPrivateSetMethod(StringBuilder output, string className, IPropertySymbol property)
    {
        output.AppendLine($"        private void Set{property.Name}({className} instance, {property.Type} value)");
        output.AppendLine("        {");
        output.AppendLine($"            var property = InstanceType.GetProperty(\"{property.Name}\");");
        output.AppendLine("            if (property != null)");
        output.AppendLine("            {");
        output.AppendLine("                property.SetValue(instance, value);");
        output.AppendLine("            }");
        output.AppendLine("        }");
        output.AppendLine();
    }

    private IReadOnlyList<(ClassSymbol ClassSymbol, FluentData FluentData)> GetClassSymbols()
    {
        var classSymbols = new List<(ClassSymbol ClassSymbol, FluentData FluentData)>();
        foreach (var fluentDataItem in _receiver.CandidateFluentDataItems)
        {
            if (_context.TryGetNamedTypeSymbolByFullMetadataName(fluentDataItem, out var classSymbol))
            {
                classSymbols.Add((classSymbol, fluentDataItem));
            }
        }

        return classSymbols;
    }

    private static string CamelCase(string value) => $"{value.Substring(0, 1).ToLowerInvariant()}{value.Substring(1)}";
}