namespace FluentBuilderGenerator.FileGenerators;

internal static class Header
{
    public static string Text =
        $"""
         //------------------------------------------------------------------------------
         // <auto-generated>
         //     This code was generated by https://github.com/StefH/FluentBuilder version {System.Reflection.Assembly.GetExecutingAssembly().GetName().Version}
         //
         //     Changes to this file may cause incorrect behavior and will be lost if
         //     the code is regenerated.
         // </auto-generated>
         //------------------------------------------------------------------------------
         """;
}