using FluentBuilderGenerator.Models;
using FluentBuilderGenerator.Types;

namespace FluentBuilderGenerator.FileGenerators;

// ReSharper disable once InconsistentNaming
internal class IEnumerableBuilderGenerator : IFileGenerator
{
    private readonly FileDataType _dataType;
    private readonly bool _supportsNullable;
    private readonly string _className;
    private readonly string _genericType;
    private readonly string _toArray;

    public IEnumerableBuilderGenerator(FileDataType dataType, bool supportsNullable)
    {
        _dataType = dataType;
        _supportsNullable = supportsNullable;
        _className = dataType.ToString();

        switch (dataType)
        {
            case FileDataType.ArrayBuilder:
                _genericType = "T[]";
                _toArray = ".ToArray()";
                break;

            case FileDataType.IEnumerableBuilder:
                _genericType = "IEnumerable<T>";
                _toArray = string.Empty;
                break;

            case FileDataType.ICollectionBuilder:
                _genericType = "ICollection<T>";
                _toArray = string.Empty;
                break;

            case FileDataType.IListBuilder:
                _genericType = "IList<T>";
                _toArray = string.Empty;
                break;

            default:
                throw new ArgumentException();
        }
    }

    public FileData GenerateFile()
    {
        return new FileData
        (
            _dataType,
            $"FluentBuilder.{_className}.g.cs",
            $@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/FluentBuilder.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

{(_supportsNullable ? "#nullable enable" : string.Empty)}
using System;
using System.Collections.Generic;

namespace FluentBuilder
{{
    public partial class {_className}<T> : Builder<{_genericType}>
    {{
        protected readonly Lazy<List<T>> _list = new Lazy<List<T>>(() => new List<T>());

        public virtual {_className}<T> Add(T item) => Add(() => item);
        public virtual {_className}<T> Add(Func<T> func)
        {{
            _list.Value.Add(func());

            return this;
        }}

        public override {_genericType} Build(bool useObjectInitializer = true)
        {{
            if (Object?.IsValueCreated != true)
            {{
                Object = new Lazy<{_genericType}>(() =>
                {{
                    return _list.Value{_toArray};
                }});
            }}

            PostBuild(Object.Value);

            return Object.Value;
        }}
    }}
}}
{(_supportsNullable ? "#nullable disable" : string.Empty)}"
        );
    }
}