//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/FluentBuilder version 0.7.1.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using FluentBuilderGeneratorTests.FluentBuilder;
using AbcTest.OtherNamespace;

namespace AbcTest.OtherNamespace
{
    public partial class ClassOnOtherNamespaceBuilder : Builder<AbcTest.OtherNamespace.ClassOnOtherNamespace>
    {
        private bool _idIsSet;
        private Lazy<int> _id = new Lazy<int>(() => default(int));
        public ClassOnOtherNamespaceBuilder WithId(int value) => WithId(() => value);
        public ClassOnOtherNamespaceBuilder WithId(Func<int> func)
        {
            _id = new Lazy<int>(func);
            _idIsSet = true;
            return this;
        }
        public ClassOnOtherNamespaceBuilder WithoutId()
        {
            WithId(() => default(int));
            _idIsSet = false;
            return this;
        }


        private bool _Constructor1204632294_IsSet;
        private Lazy<AbcTest.OtherNamespace.ClassOnOtherNamespace> _Constructor1204632294 = new Lazy<AbcTest.OtherNamespace.ClassOnOtherNamespace>(() => new AbcTest.OtherNamespace.ClassOnOtherNamespace());
        public ClassOnOtherNamespaceBuilder UsingConstructor()
        {
            _Constructor1204632294 = new Lazy<AbcTest.OtherNamespace.ClassOnOtherNamespace>(() =>
            {
                return new AbcTest.OtherNamespace.ClassOnOtherNamespace
                (

                );
            });
            _Constructor1204632294_IsSet = true;

            return this;
        }


        public override ClassOnOtherNamespace Build() => Build(true);

        public override ClassOnOtherNamespace Build(bool useObjectInitializer)
        {
            if (Object?.IsValueCreated != true)
            {
                Object = new Lazy<ClassOnOtherNamespace>(() =>
                {
                    ClassOnOtherNamespace instance;
                    if (useObjectInitializer)
                    {
                        instance = new ClassOnOtherNamespace
                        {
                            Id = _id.Value
                        };

                        return instance;
                    }

                    if (_Constructor1204632294_IsSet) { instance = _Constructor1204632294.Value; }
                    else { instance = Default(); }

                    if (_idIsSet) { instance.Id = _id.Value; }

                    return instance;
                });
            }

            PostBuild(Object.Value);

            return Object.Value;
        }

        public static ClassOnOtherNamespace Default() => new ClassOnOtherNamespace();

    }
}
#nullable disable