//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/FluentBuilder.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
using System;
using System.Collections;
using System.Collections.Generic;
using FluentBuilder;
using FluentBuilderGeneratorTests.DTO;

namespace FluentBuilder
{
    public partial class AddressBuilder : Builder<Address>
    {
        private bool _houseNumberIsSet;
        private Lazy<int> _houseNumber = new Lazy<int>(() => default(int));
        public AddressBuilder WithHouseNumber(int value) => WithHouseNumber(() => value);
        public AddressBuilder WithHouseNumber(Func<int> func)
        {
            _houseNumber = new Lazy<int>(func);
            _houseNumberIsSet = true;
            return this;
        }
        public AddressBuilder WithoutHouseNumber()
        {
            WithHouseNumber(() => default(int));
            _houseNumberIsSet = false;
            return this;
        }

        private bool _cityIsSet;
        private Lazy<string> _city = new Lazy<string>(() => default(string));
        public AddressBuilder WithCity(string value) => WithCity(() => value);
        public AddressBuilder WithCity(Func<string> func)
        {
            _city = new Lazy<string>(func);
            _cityIsSet = true;
            return this;
        }
        public AddressBuilder WithoutCity()
        {
            WithCity(() => default(string));
            _cityIsSet = false;
            return this;
        }

        private bool _arrayIsSet;
        private Lazy<string[]> _array = new Lazy<string[]>(() => default(string[]));
        public AddressBuilder WithArray(string[] value) => WithArray(() => value);
        public AddressBuilder WithArray(Func<string[]> func)
        {
            _array = new Lazy<string[]>(func);
            _arrayIsSet = true;
            return this;
        }
        public AddressBuilder WithArray(Action<FluentBuilder.IEnumerableBuilder<String>> action, bool useObjectInitializer = true) => WithArray(() =>
        {
            var builder = new FluentBuilder.IEnumerableBuilder<String>();
            action(builder);
            return (string[]) builder.Build(useObjectInitializer);
        });
        public AddressBuilder WithoutArray()
        {
            WithArray(() => default(string[]));
            _arrayIsSet = false;
            return this;
        }

        private bool _listIsSet;
        private Lazy<System.Collections.Generic.List<string>> _list = new Lazy<System.Collections.Generic.List<string>>(() => default(System.Collections.Generic.List<string>));
        public AddressBuilder WithList(System.Collections.Generic.List<string> value) => WithList(() => value);
        public AddressBuilder WithList(Func<System.Collections.Generic.List<string>> func)
        {
            _list = new Lazy<System.Collections.Generic.List<string>>(func);
            _listIsSet = true;
            return this;
        }
        public AddressBuilder WithList(Action<FluentBuilder.IEnumerableBuilder<String>> action, bool useObjectInitializer = true) => WithList(() =>
        {
            var builder = new FluentBuilder.IEnumerableBuilder<String>();
            action(builder);
            return (System.Collections.Generic.List<string>) builder.Build(useObjectInitializer);
        });
        public AddressBuilder WithoutList()
        {
            WithList(() => default(System.Collections.Generic.List<string>));
            _listIsSet = false;
            return this;
        }

        private bool _iListAddressIsSet;
        private Lazy<System.Collections.Generic.IList<FluentBuilderGeneratorTests.DTO.Address>> _iListAddress = new Lazy<System.Collections.Generic.IList<FluentBuilderGeneratorTests.DTO.Address>>(() => default(System.Collections.Generic.IList<FluentBuilderGeneratorTests.DTO.Address>));
        public AddressBuilder WithIListAddress(System.Collections.Generic.IList<FluentBuilderGeneratorTests.DTO.Address> value) => WithIListAddress(() => value);
        public AddressBuilder WithIListAddress(Func<System.Collections.Generic.IList<FluentBuilderGeneratorTests.DTO.Address>> func)
        {
            _iListAddress = new Lazy<System.Collections.Generic.IList<FluentBuilderGeneratorTests.DTO.Address>>(func);
            _iListAddressIsSet = true;
            return this;
        }
        public AddressBuilder WithIListAddress(Action<FluentBuilder.IEnumerableAddressBuilder> action, bool useObjectInitializer = true) => WithIListAddress(() =>
        {
            var builder = new FluentBuilder.IEnumerableAddressBuilder();
            action(builder);
            return (System.Collections.Generic.IList<FluentBuilderGeneratorTests.DTO.Address>) builder.Build(useObjectInitializer);
        });
        public AddressBuilder WithoutIListAddress()
        {
            WithIListAddress(() => default(System.Collections.Generic.IList<FluentBuilderGeneratorTests.DTO.Address>));
            _iListAddressIsSet = false;
            return this;
        }

        private bool _dictionaryIsSet;
        private Lazy<System.Collections.IDictionary> _dictionary = new Lazy<System.Collections.IDictionary>(() => default(System.Collections.IDictionary));
        public AddressBuilder WithDictionary(System.Collections.IDictionary value) => WithDictionary(() => value);
        public AddressBuilder WithDictionary(Func<System.Collections.IDictionary> func)
        {
            _dictionary = new Lazy<System.Collections.IDictionary>(func);
            _dictionaryIsSet = true;
            return this;
        }
        public AddressBuilder WithoutDictionary()
        {
            WithDictionary(() => default(System.Collections.IDictionary));
            _dictionaryIsSet = false;
            return this;
        }

        private bool _dictionary2IsSet;
        private Lazy<System.Collections.Generic.IDictionary<string, int>> _dictionary2 = new Lazy<System.Collections.Generic.IDictionary<string, int>>(() => default(System.Collections.Generic.IDictionary<string, int>));
        public AddressBuilder WithDictionary2(System.Collections.Generic.IDictionary<string, int> value) => WithDictionary2(() => value);
        public AddressBuilder WithDictionary2(Func<System.Collections.Generic.IDictionary<string, int>> func)
        {
            _dictionary2 = new Lazy<System.Collections.Generic.IDictionary<string, int>>(func);
            _dictionary2IsSet = true;
            return this;
        }
        public AddressBuilder WithDictionary2(Action<FluentBuilder.IDictionaryBuilder<String, Int32>> action, bool useObjectInitializer = true) => WithDictionary2(() =>
        {
            var builder = new FluentBuilder.IDictionaryBuilder<String, Int32>();
            action(builder);
            return builder.Build(useObjectInitializer);
        });
        public AddressBuilder WithoutDictionary2()
        {
            WithDictionary2(() => default(System.Collections.Generic.IDictionary<string, int>));
            _dictionary2IsSet = false;
            return this;
        }


        public override Address Build(bool useObjectInitializer = true)
        {
            if (Object?.IsValueCreated != true)
            {
                Object = new Lazy<Address>(() =>
                {
                    if (useObjectInitializer)
                    {
                        return new Address
                        {
                            HouseNumber = _houseNumber.Value,
                            City = _city.Value,
                            Array = _array.Value,
                            List = _list.Value,
                            IListAddress = _iListAddress.Value,
                            Dictionary = _dictionary.Value,
                            Dictionary2 = _dictionary2.Value
                        };
                    }

                    var instance = new Address();
                    if (_houseNumberIsSet) { instance.HouseNumber = _houseNumber.Value; }
                    if (_cityIsSet) { instance.City = _city.Value; }
                    if (_arrayIsSet) { instance.Array = _array.Value; }
                    if (_listIsSet) { instance.List = _list.Value; }
                    if (_iListAddressIsSet) { instance.IListAddress = _iListAddress.Value; }
                    if (_dictionaryIsSet) { instance.Dictionary = _dictionary.Value; }
                    if (_dictionary2IsSet) { instance.Dictionary2 = _dictionary2.Value; }
                    return instance;
                });
            }

            PostBuild(Object.Value);

            return Object.Value;
        }

        public static Address Default() => new Address();

    }
}
#nullable disable