//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/FluentBuilder version 0.4.10.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
using System;

namespace FluentBuilder
{
    [AttributeUsage(AttributeTargets.Class)]
    internal sealed class AutoGenerateBuilderAttribute : Attribute
    {
        public Type? Type { get; }

        public AutoGenerateBuilderAttribute(Type? type = null)
        {
            Type = type;
        }
    }

    [AttributeUsage(AttributeTargets.Property)]
    internal sealed class IgnorePropertyAttribute : Attribute
    {
    }
}
#nullable disable