//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/FluentBuilder version 0.5.1.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using FluentBuilderGeneratorTests.FluentBuilder;
using FluentBuilderGeneratorTests.DTO;

namespace FluentBuilderGeneratorTests.DTO
{
    public partial class ClassWithPrivateSetter1Builder : Builder<FluentBuilderGeneratorTests.DTO.ClassWithPrivateSetter1>
    {
        private bool _value2IsSet;
        private Lazy<int> _value2 = new Lazy<int>(() => default(int));
        public ClassWithPrivateSetter1Builder WithValue2(int value) => WithValue2(() => value);
        public ClassWithPrivateSetter1Builder WithValue2(Func<int> func)
        {
            _value2 = new Lazy<int>(func);
            _value2IsSet = true;
            return this;
        }
        public ClassWithPrivateSetter1Builder WithoutValue2()
        {
            WithValue2(() => default(int));
            _value2IsSet = false;
            return this;
        }

        private bool _value1IsSet;
        private Lazy<int> _value1 = new Lazy<int>(() => default(int));
        public ClassWithPrivateSetter1Builder WithValue1(int value) => WithValue1(() => value);
        public ClassWithPrivateSetter1Builder WithValue1(Func<int> func)
        {
            _value1 = new Lazy<int>(func);
            _value1IsSet = true;
            return this;
        }
        public ClassWithPrivateSetter1Builder WithoutValue1()
        {
            WithValue1(() => default(int));
            _value1IsSet = false;
            return this;
        }


        private void SetValue1(ClassWithPrivateSetter1 instance, int value)
        {
            InstanceType.GetProperty("Value1")?.SetValue(instance, value);
        }

        public override ClassWithPrivateSetter1 Build(bool useObjectInitializer = true)
        {
            if (Object?.IsValueCreated != true)
            {
                Object = new Lazy<ClassWithPrivateSetter1>(() =>
                {
                    ClassWithPrivateSetter1 instance;
                    if (useObjectInitializer)
                    {
                        instance = new ClassWithPrivateSetter1
                        {
                            Value2 = _value2.Value
                        };
                        if (_value1IsSet) { SetValue1(instance, _value1.Value); }
                        return instance;
                    }

                    instance = new ClassWithPrivateSetter1();
                    if (_value2IsSet) { instance.Value2 = _value2.Value; }
                    if (_value1IsSet) { SetValue1(instance, _value1.Value); }
                    return instance;
                });
            }

            PostBuild(Object.Value);

            return Object.Value;
        }

        public static ClassWithPrivateSetter1 Default() => new ClassWithPrivateSetter1();

    }
}
#nullable disable