//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/FluentBuilder version 0.8.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using FluentBuilderGeneratorTests.FluentBuilder;
using FluentBuilderGeneratorTests.DTO;

namespace FluentBuilderGeneratorTests.DTO
{
    public static partial class AddressBuilder_T_Extensions
    {
        public static AddressBuilder<T> AsBuilder<T>(this FluentBuilderGeneratorTests.DTO.Address<T> instance) where T : struct
        {
            return new AddressBuilder<T>().UsingInstance(instance);
        }
    }

    public partial class AddressBuilder<T> : Builder<FluentBuilderGeneratorTests.DTO.Address<T>> where T : struct
    {
        private bool _streetIsSet;
        private Lazy<T> _street = new Lazy<T>(() => default(T));
        public AddressBuilder<T> WithStreet(T value) => WithStreet(() => value);
        public AddressBuilder<T> WithStreet(Func<T> func)
        {
            _street = new Lazy<T>(func);
            _streetIsSet = true;
            return this;
        }

        private bool _Constructor478882805_IsSet;
        private Lazy<FluentBuilderGeneratorTests.DTO.Address<T>> _Constructor478882805 = new Lazy<FluentBuilderGeneratorTests.DTO.Address<T>>(() => new FluentBuilderGeneratorTests.DTO.Address<T>());
        public AddressBuilder<T> UsingConstructor()
        {
            _Constructor478882805 = new Lazy<FluentBuilderGeneratorTests.DTO.Address<T>>(() =>
            {
                return new FluentBuilderGeneratorTests.DTO.Address<T>
                (

                );
            });
            _Constructor478882805_IsSet = true;

            return this;
        }


        public AddressBuilder<T> UsingInstance(Address<T> value) => UsingInstance(() => value);

        public AddressBuilder<T> UsingInstance(Func<Address<T>> func)
        {
            Instance = new Lazy<Address<T>>(func);
            return this;
        }

        public override Address<T> Build() => Build(true);

        public override Address<T> Build(bool useObjectInitializer)
        {
            if (Instance is null)
            {
                Instance = new Lazy<Address<T>>(() =>
                {
                    Address<T> instance;
                    if (useObjectInitializer)
                    {
                        instance = new Address<T>
                        {
                            Street = _street.Value
                        };

                        return instance;
                    }

                    if (_Constructor478882805_IsSet) { instance = _Constructor478882805.Value; }
                    else { instance = Default(); }

                    return instance;
                });
            }

            if (_streetIsSet) { Instance.Value.Street = _street.Value; }

            PostBuild(Instance.Value);

            return Instance.Value;
        }

        public static Address<T> Default() => new Address<T>();

    }
}
#nullable disable