//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/FluentBuilder.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace FluentBuilder
{
    [AttributeUsage(AttributeTargets.Class)]
    sealed class AutoGenerateBuilderAttribute : Attribute
    {
        public AutoGenerateBuilderAttribute() {}
    }
}