//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/FluentBuilder version 0.5.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
using System;

namespace FluentBuilder
{
    [AttributeUsage(AttributeTargets.Class)]
    internal sealed class AutoGenerateBuilderAttribute : Attribute
    {
        public Type? Type { get; }
        public bool HandleBaseClasses { get; }

        public AutoGenerateBuilderAttribute(bool handleBaseClasses = true) : this(null, handleBaseClasses)
        {
        }

        public AutoGenerateBuilderAttribute(Type? type) : this(type, false)
        {
        }

        public AutoGenerateBuilderAttribute(Type? type, bool handleBaseClasses = true)
        {
            Type = type;
            HandleBaseClasses = handleBaseClasses;
        }
    }

    [AttributeUsage(AttributeTargets.Property)]
    internal sealed class FluentBuilderIgnoreAttribute : Attribute
    {
    }
}
#nullable disable