//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/FluentBuilder version 0.10.0.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using FluentBuilderGeneratorTests.FluentBuilder;
using FluentBuilderGeneratorTests.DTO;

namespace FluentBuilderGeneratorTests.DTO
{
    public static partial class ClassWithPrimaryConstructorBuilderExtensions
    {
        public static ClassWithPrimaryConstructorBuilder AsBuilder(this FluentBuilderGeneratorTests.DTO.ClassWithPrimaryConstructor instance)
        {
            return new ClassWithPrimaryConstructorBuilder().UsingInstance(instance);
        }
    }

    public partial class ClassWithPrimaryConstructorBuilder : Builder<FluentBuilderGeneratorTests.DTO.ClassWithPrimaryConstructor>
    {
        private Lazy<string> _test = new Lazy<string>(() => string.Empty);
        public ClassWithPrimaryConstructorBuilder WithTest(string value) => WithTest(() => value);
        public ClassWithPrimaryConstructorBuilder WithTest(Func<string> func)
        {
            _test = new Lazy<string>(func);
            return this;
        }
        private Lazy<int> _num = new Lazy<int>(() => default(int));
        public ClassWithPrimaryConstructorBuilder WithNum(int value) => WithNum(() => value);
        public ClassWithPrimaryConstructorBuilder WithNum(Func<int> func)
        {
            _num = new Lazy<int>(func);
            return this;
        }
        private bool _normalIsSet;
        private Lazy<string> _normal = new Lazy<string>(() => string.Empty);
        public ClassWithPrimaryConstructorBuilder WithNormal(string value) => WithNormal(() => value);
        public ClassWithPrimaryConstructorBuilder WithNormal(Func<string> func)
        {
            _normal = new Lazy<string>(func);
            _normalIsSet = true;
            return this;
        }

        private bool _Constructor827069805_IsSet;
        private Lazy<FluentBuilderGeneratorTests.DTO.ClassWithPrimaryConstructor> _Constructor827069805 = new Lazy<FluentBuilderGeneratorTests.DTO.ClassWithPrimaryConstructor>(() => new FluentBuilderGeneratorTests.DTO.ClassWithPrimaryConstructor(string.Empty, default(int)));
        public ClassWithPrimaryConstructorBuilder UsingConstructor(string test, int num)
        {
            _Constructor827069805 = new Lazy<FluentBuilderGeneratorTests.DTO.ClassWithPrimaryConstructor>(() =>
            {
                return new FluentBuilderGeneratorTests.DTO.ClassWithPrimaryConstructor
                (
                    test, 
                    num
                );
            });
            _Constructor827069805_IsSet = true;

            return this;
        }


        public ClassWithPrimaryConstructorBuilder UsingInstance(ClassWithPrimaryConstructor value) => UsingInstance(() => value);

        public ClassWithPrimaryConstructorBuilder UsingInstance(Func<ClassWithPrimaryConstructor> func)
        {
            Instance = new Lazy<ClassWithPrimaryConstructor>(func);
            return this;
        }

        public override ClassWithPrimaryConstructor Build() => Build(false);

        public override ClassWithPrimaryConstructor Build(bool useObjectInitializer)
        {
            if (Instance is null)
            {
                Instance = new Lazy<ClassWithPrimaryConstructor>(() =>
                {
                    ClassWithPrimaryConstructor instance;
                    if (useObjectInitializer)
                    {
                        throw new NotSupportedException("Unable to use the ObjectInitializer for the class 'FluentBuilderGeneratorTests.DTO.ClassWithPrimaryConstructor' because no public parameterless constructor is defined.");
                    }

                    if (_Constructor827069805_IsSet) { instance = _Constructor827069805.Value; }
                    else { instance = new ClassWithPrimaryConstructor(_test.Value, _num.Value); }

                    return instance;
                });
            }

            if (_normalIsSet) { Instance.Value.Normal = _normal.Value; }

            PostBuild(Instance.Value);

            return Instance.Value;
        }

        public static ClassWithPrimaryConstructor Default() => new ClassWithPrimaryConstructor(string.Empty, default(int));

    }
}
#nullable disable