//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/FluentBuilder version 0.5.1.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using FluentBuilderGeneratorTests.FluentBuilder;
using FluentBuilderGeneratorTests.DTO;

namespace FluentBuilderGeneratorTests.DTO
{
    public partial class ClassWithPrivateSetter2Builder : Builder<FluentBuilderGeneratorTests.DTO.ClassWithPrivateSetter2>
    {
        private bool _value2IsSet;
        private Lazy<int> _value2 = new Lazy<int>(() => default(int));
        public ClassWithPrivateSetter2Builder WithValue2(int value) => WithValue2(() => value);
        public ClassWithPrivateSetter2Builder WithValue2(Func<int> func)
        {
            _value2 = new Lazy<int>(func);
            _value2IsSet = true;
            return this;
        }
        public ClassWithPrivateSetter2Builder WithoutValue2()
        {
            WithValue2(() => default(int));
            _value2IsSet = false;
            return this;
        }

        private bool _value1IsSet;
        private Lazy<int> _value1 = new Lazy<int>(() => default(int));
        public ClassWithPrivateSetter2Builder WithValue1(int value) => WithValue1(() => value);
        public ClassWithPrivateSetter2Builder WithValue1(Func<int> func)
        {
            _value1 = new Lazy<int>(func);
            _value1IsSet = true;
            return this;
        }
        public ClassWithPrivateSetter2Builder WithoutValue1()
        {
            WithValue1(() => default(int));
            _value1IsSet = false;
            return this;
        }


        private void SetValue1(ClassWithPrivateSetter2 instance, int value)
        {
            var property = InstanceType.GetProperty("Value1");
            if (property != null)
            {
                property.SetValue(instance, value);
            }
        }

        public override ClassWithPrivateSetter2 Build(bool useObjectInitializer = true)
        {
            if (Object?.IsValueCreated != true)
            {
                Object = new Lazy<ClassWithPrivateSetter2>(() =>
                {
                    ClassWithPrivateSetter2 instance;
                    if (useObjectInitializer)
                    {
                        instance = new ClassWithPrivateSetter2
                        {
                            Value2 = _value2.Value
                        };
                        if (_value1IsSet) { SetValue1(instance, _value1.Value); }
                        return instance;
                    }

                    instance = new ClassWithPrivateSetter2();
                    if (_value2IsSet) { instance.Value2 = _value2.Value; }
                    if (_value1IsSet) { SetValue1(instance, _value1.Value); }
                    return instance;
                });
            }

            PostBuild(Object.Value);

            return Object.Value;
        }

        public static ClassWithPrivateSetter2 Default() => new ClassWithPrivateSetter2();

    }
}
#nullable disable