//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/FluentBuilder version 0.5.1.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
using System;

namespace FluentBuilder
{
    [AttributeUsage(AttributeTargets.Class)]
    internal sealed class AutoGenerateBuilderAttribute : Attribute
    {
        public Type? Type { get; }
        public bool HandleBaseClasses { get; }
        public FluentBuilderAccessibility Accessibility { get; }

        public AutoGenerateBuilderAttribute() : this(null, true, FluentBuilderAccessibility.Public)
        {
        }

        public AutoGenerateBuilderAttribute(bool handleBaseClasses) : this(null, handleBaseClasses, FluentBuilderAccessibility.Public)
        {
        }

        public AutoGenerateBuilderAttribute(FluentBuilderAccessibility accessibility) : this(null, true, accessibility)
        {
        }

        public AutoGenerateBuilderAttribute(bool handleBaseClasses, FluentBuilderAccessibility accessibility) : this(null, handleBaseClasses, accessibility)
        {
        }

        public AutoGenerateBuilderAttribute(Type? type) : this(type, true, FluentBuilderAccessibility.Public)
        {
        }

        public AutoGenerateBuilderAttribute(Type? type, FluentBuilderAccessibility accessibility) : this(type, true, accessibility)
        {
        }

        public AutoGenerateBuilderAttribute(Type? type, bool handleBaseClasses, FluentBuilderAccessibility accessibility = FluentBuilderAccessibility.Public)
        {
            Type = type;
            HandleBaseClasses = handleBaseClasses;
            Accessibility = accessibility;
        }
    }

    [AttributeUsage(AttributeTargets.Property)]
    internal sealed class FluentBuilderIgnoreAttribute : Attribute
    {
    }

    [Flags]
    internal enum FluentBuilderAccessibility
    {
        Public = 0,
        PublicAndPrivate = 1
    }
}
#nullable disable