//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/FluentBuilder version 0.15.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using FluentBuilderGeneratorTests.FluentBuilder;
using FluentBuilderGeneratorTests.DTO;

namespace FluentBuilderGeneratorTests.DTO
{
    public static partial class ClassWithConstructorParamMatchingPropertyBuilderExtensions
    {
        public static ClassWithConstructorParamMatchingPropertyBuilder AsBuilder(this FluentBuilderGeneratorTests.DTO.ClassWithConstructorParamMatchingProperty instance)
        {
            return new ClassWithConstructorParamMatchingPropertyBuilder().UsingInstance(instance);
        }
    }

    public partial class ClassWithConstructorParamMatchingPropertyBuilder : Builder<FluentBuilderGeneratorTests.DTO.ClassWithConstructorParamMatchingProperty>
    {
        private bool _typeIsSet;
        private Lazy<FluentBuilderGeneratorTests.DTO.StageType> _type = new Lazy<FluentBuilderGeneratorTests.DTO.StageType>(() => default(FluentBuilderGeneratorTests.DTO.StageType));
        public ClassWithConstructorParamMatchingPropertyBuilder WithType(FluentBuilderGeneratorTests.DTO.StageType value) => WithType(() => value);
        public ClassWithConstructorParamMatchingPropertyBuilder WithType(Func<FluentBuilderGeneratorTests.DTO.StageType> func)
        {
            _type = new Lazy<FluentBuilderGeneratorTests.DTO.StageType>(func);
            _typeIsSet = true;
            return this;
        }
        private bool _nameIsSet;
        private Lazy<string> _name = new Lazy<string>(() => string.Empty);
        public ClassWithConstructorParamMatchingPropertyBuilder WithName(string value) => WithName(() => value);
        public ClassWithConstructorParamMatchingPropertyBuilder WithName(Func<string> func)
        {
            _name = new Lazy<string>(func);
            _nameIsSet = true;
            return this;
        }

        private bool _Constructor1653456255_IsSet;
        private Lazy<FluentBuilderGeneratorTests.DTO.ClassWithConstructorParamMatchingProperty> _Constructor1653456255 = new Lazy<FluentBuilderGeneratorTests.DTO.ClassWithConstructorParamMatchingProperty>(() => new FluentBuilderGeneratorTests.DTO.ClassWithConstructorParamMatchingProperty(default(FluentBuilderGeneratorTests.DTO.StageType))
        {

        });
        public ClassWithConstructorParamMatchingPropertyBuilder UsingConstructor(FluentBuilderGeneratorTests.DTO.StageType @type)
        {
            _Constructor1653456255 = new Lazy<FluentBuilderGeneratorTests.DTO.ClassWithConstructorParamMatchingProperty>(() =>
            {
                return new FluentBuilderGeneratorTests.DTO.ClassWithConstructorParamMatchingProperty
                (
                    type
                )
                {

                };
            });
            _Constructor1653456255_IsSet = true;

            return this;
        }


        public ClassWithConstructorParamMatchingPropertyBuilder UsingInstance(ClassWithConstructorParamMatchingProperty value) => UsingInstance(() => value);

        public ClassWithConstructorParamMatchingPropertyBuilder UsingInstance(Func<ClassWithConstructorParamMatchingProperty> func)
        {
            Instance = new Lazy<ClassWithConstructorParamMatchingProperty>(func);
            return this;
        }

        public override ClassWithConstructorParamMatchingProperty Build() => Build(false);

        public override ClassWithConstructorParamMatchingProperty Build(bool useObjectInitializer)
        {
            if (Instance is null)
            {
                Instance = new Lazy<ClassWithConstructorParamMatchingProperty>(() =>
                {
                    ClassWithConstructorParamMatchingProperty instance;
                    if (useObjectInitializer)
                    {
                        throw new NotSupportedException("Unable to use the ObjectInitializer for the class 'FluentBuilderGeneratorTests.DTO.ClassWithConstructorParamMatchingProperty' because no public parameterless constructor is defined.");
                    }

                    if (_Constructor1653456255_IsSet) { instance = _Constructor1653456255.Value; }
                    else { instance = new ClassWithConstructorParamMatchingProperty(_type.Value); }

                    return instance;
                });
            }

            if (_typeIsSet) { Instance.Value.Type = _type.Value; }
            if (_nameIsSet) { Instance.Value.Name = _name.Value; }

            PostBuild(Instance.Value);

            return Instance.Value;
        }

        public static ClassWithConstructorParamMatchingProperty Default() => new ClassWithConstructorParamMatchingProperty(default(FluentBuilderGeneratorTests.DTO.StageType))
        {

        };

    }
}
#nullable disable