//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/FluentBuilder version 0.9.2.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using FluentBuilderGeneratorTests.FluentBuilder;
using FluentBuilderGeneratorTests.DTO;

namespace FluentBuilderGeneratorTests.DTO
{
    public static partial class ClassWithInitBuilderExtensions
    {
        public static ClassWithInitBuilder AsBuilder(this FluentBuilderGeneratorTests.DTO.ClassWithInit instance)
        {
            return new ClassWithInitBuilder().UsingInstance(instance);
        }
    }

    public partial class ClassWithInitBuilder : Builder<FluentBuilderGeneratorTests.DTO.ClassWithInit>
    {
        private bool _normalIsSet;
        private Lazy<string> _normal = new Lazy<string>(() => string.Empty);
        public ClassWithInitBuilder WithNormal(string value) => WithNormal(() => value);
        public ClassWithInitBuilder WithNormal(Func<string> func)
        {
            _normal = new Lazy<string>(func);
            _normalIsSet = true;
            return this;
        }

        private bool _Constructor_92937217_IsSet;
        private Lazy<FluentBuilderGeneratorTests.DTO.ClassWithInit> _Constructor_92937217 = new Lazy<FluentBuilderGeneratorTests.DTO.ClassWithInit>(() => new FluentBuilderGeneratorTests.DTO.ClassWithInit());
        public ClassWithInitBuilder UsingConstructor()
        {
            _Constructor_92937217 = new Lazy<FluentBuilderGeneratorTests.DTO.ClassWithInit>(() =>
            {
                return new FluentBuilderGeneratorTests.DTO.ClassWithInit
                (

                );
            });
            _Constructor_92937217_IsSet = true;

            return this;
        }


        public ClassWithInitBuilder UsingInstance(ClassWithInit value) => UsingInstance(() => value);

        public ClassWithInitBuilder UsingInstance(Func<ClassWithInit> func)
        {
            Instance = new Lazy<ClassWithInit>(func);
            return this;
        }

        public override ClassWithInit Build() => Build(true);

        public override ClassWithInit Build(bool useObjectInitializer)
        {
            if (Instance is null)
            {
                Instance = new Lazy<ClassWithInit>(() =>
                {
                    ClassWithInit instance;
                    if (useObjectInitializer)
                    {
                        instance = new ClassWithInit
                        {
                            Normal = _normal.Value
                        };

                        return instance;
                    }

                    if (_Constructor_92937217_IsSet) { instance = _Constructor_92937217.Value; }
                    else { instance = Default(); }

                    return instance;
                });
            }

            if (_normalIsSet) { Instance.Value.Normal = _normal.Value; }

            PostBuild(Instance.Value);

            return Instance.Value;
        }

        public static ClassWithInit Default() => new ClassWithInit();

    }
}
#nullable disable