name: Build and Test

on: 
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - 'main'

jobs:
  build-and-test:
    name: Build and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]

    steps:
    - uses: actions/checkout@v4
  
    - name: Setup .NET 8 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: 'Build'
      run: dotnet build ./FluentBuilder Solution.sln -c Release

    - name: 'Test'
      run: dotnet test ./tests/FluentBuilderGeneratorTests/FluentBuilderGeneratorTests.csproj --no-build -c Release