//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/FluentBuilder version 0.6.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
using System;
using System.Collections;
using System.Collections.Generic;
using FluentBuilderGeneratorTests.FluentBuilder;
using FluentBuilderGeneratorTests.DTO;

namespace FluentBuilderGeneratorTests.DTO2
{
    public partial class IListOptionBuilder : Builder<IList<FluentBuilderGeneratorTests.DTO.Option>>
    {
        private readonly Lazy<List<FluentBuilderGeneratorTests.DTO.Option>> _list = new Lazy<List<FluentBuilderGeneratorTests.DTO.Option>>(() => new List<FluentBuilderGeneratorTests.DTO.Option>());
        public IListOptionBuilder Add(Option item) => Add(() => item);
        public IListOptionBuilder Add(Func<Option> func)
        {
            _list.Value.Add(func());
            return this;
        }
        public IListOptionBuilder Add(Action<MyOptionBuilder> action, bool useObjectInitializer = true)
        {
            var builder = new MyOptionBuilder();
            action(builder);
            Add(() => builder.Build(useObjectInitializer));
            return this;
        }


        public override IList<FluentBuilderGeneratorTests.DTO.Option> Build(bool useObjectInitializer = true)
        {
            if (Object?.IsValueCreated != true)
            {
                Object = new Lazy<IList<FluentBuilderGeneratorTests.DTO.Option>>(() =>
                {
                    return _list.Value;
                });
            }

            PostBuild(Object.Value);

            return Object.Value;
        }

    }
}
#nullable disable